### ISSUE TITLE
Version update on Ubuntu 18.04

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#420]
Ubuntu Software Updater automagically updates at least some of Ignition components as shown on this screen capture:

![updater](https://user-images.githubusercontent.com/4933032/82106459-5ae3b500-96de-11ea-9173-b3ba4f29feca.png)

Does this update through Software Updater substitute for or overlap with downloading the new release from github and rebuilding `catkin` workspace? 

BTW, I just noticed that there are no releases on github. Should we clone the master branch?

**Comment by mjcarroll** [comment]
> Does this update through Software Updater substitute for or overlap with downloading the new release from github and rebuilding catkin workspace?

This is updating the underlying simulation software.  Because ignition releases stay ABI-compatible, it should not be necessary to rebuild your `catkin` workspace when these packages update.  Ignition releases are separate from `subt` releases, but often have fixes or enhancements for the `subt` environment.

> BTW, I just noticed that there are no releases on github. Should we clone the master branch?

For the cave circuit, yes.  There are also corresponding branches for `urban_circuit` and `tunnel_circuit`.

**Comment by pauljurczak** [comment]
@mjcarroll  Thank you. I noticed `cave_feature_release1` branch, which is pretty fresh. Should I still favor `master` branch over it?
