### ISSUE TITLE
Marble HD2 pan_tilt camera partially clipped top 180 lines of image

### ISSUE THREAD

**Issue by knoedler** [osrf/subt#662]
![hd2clipping](https://user-images.githubusercontent.com/4065104/95684658-028ae380-0ba8-11eb-818a-4da283e38f33.png)
The top 180 lines or so of the Marble HD2 pan tilt camera are clipped for both the image and depth views.  It is not completely clipped as weird echo images sometimes show up in the top part.  Further it is not clipped exactly on a line as you can see the first unclipped line is partial.

To repeat: (the issue seems to appear in every world)
ign launch -v 4 cave_circuit.ign worldName:=cave_qual robotName1:=MHSC2 robotConfig1:=MARBLE_HD2_SENSOR_CONFIG_2
view the pan_tilt image in rviz

**Comment by knoedler** [comment]
This issue is not blocking me, so my preference would be to leave it alone it until after the cave circuit.

**Comment by arjo129** [comment]
I can confirm the clipping behavior, but it clips by a different amount for me (around 20pixels). There's also clipping on the bottom RGBD camera.

**Comment by knoedler** [comment]
Bumping this issue as the clipping has gotten worse and is sometimes over half of the image.

**Comment by nkoenig** [comment]
The cause is due to bad placement of the camera.

Current camera placement highlight by red sphere:
![bad_placement](https://user-images.githubusercontent.com/1587438/111662124-e5001c80-87cc-11eb-867b-c45d53308e42.png)

New camera placement highlight by red sphere:
![good_placement](https://user-images.githubusercontent.com/1587438/111663678-470d5180-87ce-11eb-809c-93da7b9926ba.png)

See pull request #827
