### ISSUE TITLE
Simple Tunnel 2 - stuck robot under tent/base station

### ISSUE THREAD

**Issue by m3d** [osrf/subt#818]
I see strange situation in currently running simulation `cbc627d5-0ae0-4403-a132-4be7d4da1b00` (robotika), where the robot "accidently" explored the starting area and got stuck under the tent:
![stacked-teambase](https://user-images.githubusercontent.com/5664353/111000512-74976c80-8382-11eb-8614-9d3424b37594.jpg)
I can see wheels turning but robot is not moving ...
(I will know more when the run is over, maybe)

**Comment by iche033** [comment]
turns out to be an issue with the collisions:

![base_station_collisions](https://user-images.githubusercontent.com/4000684/111012365-ab548f00-8350-11eb-938e-b810034e4d94.png)

I've just fixed the collisions and uploaded the model onto Fuel: https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Base%20Station

**Comment by m3d** [comment]
Thanks - from our side it was rather "accident", but thanks for fix (I am not sure if I can easily reproduce it)
